export default [
	{
		'id':'1',
		'name':'盆子',
		'title':['猫咪的盆子'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/penzi1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/penzi2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/penzi3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/penzi4.png',
				'price':1
			}
		]
	},
	{
		'id':'2',
		'name':'食物',
		'title':['猫咪的食物'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/food1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/food2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/food3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/food4.png',
				'price':1
			}
		]
	},
	{
		'id':'3',
		'name':'玩具',
		'title':['猫咪的玩具'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/wanju1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/wanju2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/wanju3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/wanju4.png',
				'price':1
			}
		]
	},
	{
		'id':'4',
		'name':'小屋',
		'title':['猫咪的小屋'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/house1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/house2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/house3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/house4.png',
				'price':1
			}
		]
	},
	{
		'id':'5',
		'name':'衣服',
		'title':['猫咪的衣服'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/clothe1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/cloth2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/cloth3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/cloth4.png',
				'price':1
			}
		]
	},
	{
		'id':'6',
		'name':'好朋友',
		'title':['猫咪的好朋友'],
		'goods':[
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/friend1.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/friend2.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/friend3.png',
				'price':1
			},
			{
				'img':'https://chatcat-1312908194.cos.ap-shanghai.myqcloud.com/friend4.png',
				'price':1
			}
		]
	}
	
]
